### ISSUE TITLE
"Show hidden resources" still valid?

### ISSUE THREAD

**Issue by ultraJeff** [OpenShiftDemos/openshift-gitops-workshop#20]
This callout. I could never find anything remotely calling out "show hidden resources." Just want to check that the current Argo version still has this, and if it does, perhaps we capitalize the phrase.
![image](https://user-images.githubusercontent.com/2943566/226061740-93076065-8d45-4945-ac65-68b0e22d68d4.png)

**Comment by gnunn1** [comment]
Fixed
