### ISSUE TITLE
More waypoints in navigation

### ISSUE THREAD

**Issue by ultraJeff** [OpenShiftDemos/openshift-gitops-workshop#21]
It would be great to provide users with more waypoints in the left navigation bar.
For instance, in chapter `2. GitOps Basics,` the sections end abruptly after _Deploy a Sample Application_ even though you are less than halfway down the page.

**Comment by gnunn1** [comment]
I think the intent is for the left bar to the be the major topics, there are more navigation points on the right bar as per this screenshot which seems fine to me? Let me know what you think
![Screenshot from 2023-04-27 11-47-01](https://user-images.githubusercontent.com/9358238/234962393-50a919fa-ef91-4808-b67a-ef0364212205.png)

**Comment by ultraJeff** [comment]
Oh wow, I didn't notice the navigation bar on the right. That's helpful and fulfills what I was thinking when I wrote this, but it does feel a little strange to have two navigation panes across the way from one another. Perhaps that's just a feature of the blogging engine though; the text wrapping of section titles could get intense with yet another layer of indentation. I'll close this out. Thanks for reviewing it!
