### ISSUE TITLE
Hardcoded user1 in Helm Documentation

### ISSUE THREAD

**Issue by geoffallendev** [OpenShiftDemos/openshift-gitops-workshop#36]
There are a few instances of 'user1' being hardcoded in the templates, examples and commands in the Helm documentation.  Just caused a little confusion during the labs.

Just search for user1 in this - 
[https://github.com/OpenShiftDemos/openshift-gitops-workshop/blob/master/documentation/modules/ROOT/pages/04-helm.adoc](https://github.com/OpenShiftDemos/openshift-gitops-workshop/blob/master/documentation/modules/ROOT/pages/04-helm.adoc)

**Comment by gnunn1** [comment]
Fixed with your PR, thanks!
