### ISSUE TITLE
Publish the link to the lab content as part of the RHPDS output

### ISSUE THREAD

**Issue by gnunn1** [OpenShiftDemos/openshift-gitops-workshop#4]
It took me a good 15 minutes of digging around to figure the labs are being pushed to github pages rather then being hosted in a homeroom environment. It would be nice if the RHPDS output included a link to the lab material so folks don't need to hunt for it which I believe is located here:

https://openshiftdemos.github.io/openshift-gitops-workshop/openshift-gitops-workshop/index.html

**Comment by gnunn1** [comment]
Actually the impression I'm getting is this content is intended to be run in cluster since it tokenizes the user number everywhere as `%USERNUM%`.  Replacing this manually when running through the labs is a bit of a pain.

**Comment by thoraxe** [comment]
I think you got to it before the PR got merged that would output this. It's _supposeD_ to do this.

**Comment by thoraxe** [comment]
Appears to be fixed as of my last provision.
