### ISSUE TITLE
Use OpenShift login rather than extract secrets

### ISSUE THREAD

**Issue by gnunn1** [OpenShiftDemos/openshift-gitops-workshop#5]
If the lab is going to enable OpenShift login it should setup the Argo CD RBAC to support this and skip the secret extraction requirements for the admin user to simplify the lab workflow.

**Comment by thoraxe** [comment]
We can have this as an RFE. I just needed to port what was already there quick-and-dirty. I like the idea.

**Comment by gnunn1** [comment]
Fixed.
